services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme-2
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=email@example.com
    restart: unless-stopped
    volumes_from:
      - nginx-proxy

  hello-world:
    image: nginx:alpine
    container_name: hello-world
    volumes:
      - ./html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=servicelinktech.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=exampledomain.com
      - LETSENCRYPT_EMAIL=email@example.com
    restart: unless-stopped

volumes:
  acme:
