services:
  hello-world:
    image: nginx:alpine
    container_name: hello-world
    # ports:
    #   - "5000:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    # restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro